### ISSUE TITLE
[BUG] Sort by line name is in lexicographical order

### ISSUE THREAD

**Issue by kiran-evans** [klyte45/ImprovedTransportManager#10]
**Describe the bug**
When you sort by line name, the lines are sorted lexicographically rather than numerically.

**To Reproduce**
1. Open public transport lines
2. Click on 'Line Name'
3. Lines are ordered lexicographically

**Game Logs**
See the "Report-a-bug Helper" button at mod options menu to get instructions about how to get it.
There are two important logs: the game main log and **also** the mod log under `<CS User appdata folder>\Klyte45Mods\_LOGS\ITM.log.txt`
I will need **both** logs
**IMPORTANT**: Get this files right after having the issue and before reopening the game!

**Screenshots**
![image](https://user-images.githubusercontent.com/11967835/216785874-5397f91a-e730-44d9-aceb-ddb62c6d321d.png)

**Comment by klyte45** [comment]
It's not actually an issue, since this is the standard sorting method (except Windows files sorting, that considers the numbers as their value not their string)

That said, this will not be fixed because there are nothing to fix. However, may be added other way to sort them by their internal number in the future (not available by now, but can be achieved by using leading zeroes in the line ID)

**Comment by kiran-evans** [comment]
It would be preferrable to put Bus Line 2 before Bus Line 10, since 10 comes after 2.

**Comment by klyte45** [comment]
The line name is available as string, not as number. Copy the lines names in an Excel sheet and try sorting, the result will be the same because the character "1" is always before the character "2", independently if there's another number after.

No sorter makes this kind of number testing - except Windows Explorer files sorting afaik. No time for this now since it's working as designed

**Comment by kiran-evans** [comment]
It's very common to sort strings numerically when they are a mix of letters and digits. You would have to use regex, though, which I understand you don't want to implement.
