### ISSUE TITLE
[BUG] Simulation Error TransportManager

### ISSUE THREAD

**Issue by jazzymaz** [klyte45/ImprovedTransportManager#13]
**Describe the bug**
This mod has caused an issue with TransportManager and has caused my game to break resulting in Simulation Error that cant be fixed even from uninstalling this mod.

**To Reproduce**
No steps as such as one day the save wouldn't load. Nothing noticeable was changed

**Game Logs**
[ITM.log.txt](https://github.com/klyte45/ImprovedTransportManager/files/10715008/ITM.log.txt)
[output_log.txt](https://github.com/klyte45/ImprovedTransportManager/files/10715009/output_log.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/13452207/218286668-62862aa7-5457-4adf-b719-aec269e43d9d.png)

**Additional context**
Iv had this mod for a week and had save and quit my game a couple times with no issues but one time i saved and quit and then i relaunched and the error appeared and I have tried alot of things to fix it. There was no game update and no workshop update to my knowledge.

**Comment by klyte45** [comment]
Well, seems that the savegame itself got corrupted, and despite the error being related to TransportManager, it doesn't seems to be related to ITM because the ITM doesn't deal directly with TransportManager data when serializing them - ITM have their own data saved in another place exactly to not change critical vanilla data. That's why it's recommended to always save the savegame in a new file (not overwriting old savegame files)

I suggest you to try the Save Our Saves mod in the workshop to try to recover the savegame, or restart you work from last valid savegame. If you find any other trace about this issue that could relate to ITM feel free to reopen this.
