### ISSUE TITLE
[FEATURE] Simple "vehicle count" slider

### ISSUE THREAD

**Issue by StarrWulfe** [klyte45/ImprovedTransportManager#4]
Please bring back the ability to adjust number of vehicles on a route by vehicle count. 

It could be as simple as creating +/- toggle buttons next to the budget percentage slider that will increase/decrease the vehicle count by 1.

**Comment by kiran-evans** [comment]
I strongly agree with this.

- I understand the desire to control vehicle count by budget
- I think your budget control system is incredible and very advanced
- However, I would like the option to be able to add and remove vehicles by count if I wanted to play that way

**Comment by klyte45** [comment]
The main issue is that would prevent using a group of budget for the line. Also, as the game works with budget, changing the length of line would raise or lower the number of vehicles naturally.

To avoid this I would need to write a whole parallel budget control that accepts fixed vehicle count. Since there are other features from TLM and IPT still missing in ITM, they will be most prioritary.

**Comment by kiran-evans** [comment]
This featured existed before. You don't need to create a new system.

**Comment by klyte45** [comment]
If it used to work correctly, the TLM would be still being maintained instead of another mod taking its place. It was not working properly and that's why it needs a new approach.

I'm simply not prioritizing this at this moment and it will require researching, it doesn't mean this won't be done. Anyway, feel free to develop the solution by yourself and open a PR to merge into the mod if you know how to do it.

**Comment by kiran-evans** [comment]
Okay I understand that. Thank you, I would love to contribute!

**Comment by klyte45** [comment]
The buttons were added in version 0.2. They are shown like this:
![image](https://user-images.githubusercontent.com/11671356/221429048-17f8ecf2-be58-4472-8378-e7a8e4e2a9ab.png)

Note this only works if the game budget setting is the default one:
![image](https://user-images.githubusercontent.com/11671356/221429098-2004cda4-125e-44ba-9d5e-bf4d971858e6.png)

OBS: As warned in the window, this count is valid when the city budget is 100%. Modifying it will change the count too.
